# -*- coding: utf-8 -*-
"""internship day2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HNp3hE79UW99MwXmfWNWa3ertSd2xCAO
"""

import pandas as pd
df=pd.read_csv('/content/boston.csv')
df

df.head()

df.tail()

df.info()

df.describe()

df.shape

df.dtypes

df['crim']

df[['crim','zn']]

df.isnull()

df.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="whitegrid")
plt.figure(figsize=(10,6))
sns.boxplot(data=df,x='rad',y='age',palette='pastel')

plt.title('Boxplot of age by rad',fontsize=16)
plt.xlabel('rad',fontsize=12)
plt.ylabel('age',fontsize=12)
plt.show()

plt.figure(figsize=(10,6))
sns.lineplot(data=df,x='rad',y='age',palette='pastel')

plt.figure(figsize=(10,6))
sns.histplot(data=df,x='rad',y='age',palette='pastel')

plt.figure(figsize=(10,6))
sns.pointplot(data=df,x='rad',y='age',palette='pastel')

plt.figure(figsize=(10,6))
sns.scatterplot(data=df,x='rad',y='age',palette='pastel')

from sklearn.preprocessing import LabelEncoder
encoded_data=df.copy()

label_encoder=LabelEncoder()
encoded_data['age_Label']=label_encoder.fit_transform(encoded_data['age'])

one_hot_encoded=pd.get_dummies(encoded_data['rad'],prefix='rad')
encoded_data=pd.concat([encoded_data,one_hot_encoded],axis=1)
attrition_mapping={0:'First',1:'Second'}

encoded_data['chas_Category'] = encoded_data['chas'].map(attrition_mapping)
print(encoded_data[['age', 'age_Label', 'rad','rad_1','rad_2','rad_3','rad_4','rad_5','rad_6','rad_7','rad_8','rad_24', 'chas', 'chas_Category']].head())

from sklearn.preprocessing import MinMaxScaler,StandardScaler
File_path='/content/boston.csv'
b_data=pd.read_csv(File_path)
numerical_columns=['zn','rad','tax']
b_data.dropna(subset=numerical_columns,inplace=True)
minmax_scaler=MinMaxScaler()
standard_scaler=StandardScaler()

b_data['zn_MinMax']=minmax_scaler.fit_transform(b_data[['zn']])
b_data['rad_MinMax']=minmax_scaler.fit_transform(b_data[['rad']])
b_data['zn_Standard']=standard_scaler.fit_transform(b_data[['zn']])
b_data['rad_Standard']=standard_scaler.fit_transform(b_data[['rad']])

b_data[['zn','zn_MinMax','rad_MinMax','zn_Standard','rad_Standard']].head()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

X=df.drop(columns=["medv"])
y=df["medv"]

from os import X_OK
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model=LinearRegression()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

r2 = r2_score(y_test, y_pred)
#rmse = mean_squared_error(y_test, y_pred, squared=False)
rmse = mean_squared_error(y_test, y_pred) ** 0.5

print(f"R² Score: {r2:.4f}")
print(f"RMSE: {rmse:.4f}")